server:
  port: 8089
spring:
  application:
    name: Snowlive-crawler
    title: Snowlive
  datasource:
      name: gaokao
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/schoolsort?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 211314
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model

