server:
  port: 8080
spring:
  application:
    name: Snowlive-crawler
    title: Snowlive

  datasource:
      name: Snowlive-crawler
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
#      url: jdbc:mysql://123.206.94.212:3306/gaokao?useUnicode=true&characterEncoding=UTF-8&useSSL=true
#      password: evil
#      url: jdbc:mysql://localhost:3306/schoolsort?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      url: jdbc:mysql://localhost:3306/gaokao?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      password: 211314
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model

dao:
  master:
    datasource:
      username: root
      url: jdbc:mysql://123.206.94.212:3306/gaokao?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      password: evil
#      url: jdbc:mysql://localhost:3306/gaokao?useUnicode=true&characterEncoding=UTF-8&useSSL=true
#      password: 211314

      driver-class-name: com.mysql.jdbc.Driver
  crawler:
    datasource:
      url: jdbc:mysql://localhost:3306/schoolsort?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 211314
      driver-class-name: com.mysql.jdbc.Driver